In [3]:
def computeEvenParity(data):
    return sum(data) % 2

data = [1,0,1,0,1,1,0,0]
parityBit = computeEvenParity(data)
print(parityBit)

transmittedData = data + [parityBit] 
print(transmittedData)

errorIndex = 3
transmittedData[errorIndex] = 1 - transmittedData[errorIndex]

print(transmittedData)

if sum(transmittedData) % 2 == 0:
    print("No error")
else:
    print("Error detected")


0
[1, 0, 1, 0, 1, 1, 0, 0, 0]
[1, 0, 1, 1, 1, 1, 0, 0, 0]
Error detected


In [10]:
import numpy as np  

def computeParity(data):
    return np.sum(data, axis=1) % 2, np.sum(data, axis=0) % 2

data = np.array([
    [1,1,1,0,],
    [1,0,1,1,],
    [0,1,1,0]
])

# print(data)

rowParity, columnParity = computeParity(data)

print(rowParity)
print(columnParity)


errorData = data.copy()
errorData[2,1] = 1 - errorData[2,1] 

newRowParity, newColumnParity = computeParity(errorData)
print(newRowParity)
print(newColumnParity)

errRow = np.where(rowParity != newRowParity)[0]
errCol = np.where(columnParity != newColumnParity)[0]

if errRow.size == 1 and errCol.size == 1:
    print("Error detected at row: ", errRow[0], " column: ", errCol[0])
    errorData[errRow[0], errCol[0]] = 1 - errorData[errRow[0], errCol[0]]
    print(errorData)
else:
    print("No error")

[1 1 0]
[0 0 1 1]
[1 1 1]
[0 1 1 1]
Error detected at row:  2  column:  1
[[1 1 1 0]
 [1 0 1 1]
 [0 1 1 0]]


In [11]:
def onesComplimentSum(a,b,bitsize=4):
    result= a + b
    if result >= (1 << bitsize):
        result = (result + 1) & ((1 << bitsize) - 1)
    return result

def calculateChecksum(data, bitsize=4):
    checksum = 0
    for i in data:
        checksum = onesComplimentSum(checksum, i, bitsize)
    return ~checksum & ((1 << bitsize) - 1)

def verifyChecksum(data, recievedChecksum, bitsize=4):
    total = 0
    for i in data:
        total = onesComplimentSum(total, i, bitsize)
    total = onesComplimentSum(total, recievedChecksum, bitsize)
    return total == (1 << bitsize) - 1

data = [0b1010, 0b0101, 0b1100, 0b0000, 0b1111]

checksum = calculateChecksum(data)
print("Checksum: ", checksum)

isValid = verifyChecksum(data, checksum)
print("Is valid: ", isValid)

    

Checksum:  3
Is valid:  True
